---

- name: install packages
  yum: name={{ item }} state=latest
  with_items:
    - unzip

- name: install go
  become: true
  unarchive:
    src: https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: True

- name: set golang path
  become: false
  lineinfile:
    dest: ~/.bash_profile
    line: "export PATH=$PATH:/usr/local/go/bin"

- name: set gopath
  become: false
  lineinfile:
    dest: ~/.bash_profile
    line: "export GOPATH={{ go_path }}"

- name: set gopath
  become: false
  lineinfile:
    dest: ~/.bash_profile
    line: "export PATH=$PATH:$GOPATH/bin"

- name: set glide
  become: false
  lineinfile:
    dest: ~/.bash_profile
    line: "export GO15VENDOREXPERIMENT=1"
